version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: telegram_user
      POSTGRES_PASSWORD: telegram_pass
      POSTGRES_DB: telegram_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
